services:
  db:
    image: postgis/postgis:16-3.4
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    image: dhis2/core:2.41.8.1
    environment:
      DHIS2_HOME: /opt/dhis2
    volumes:
      - ./config/dhis2_home:/opt/dhis2
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
